### ISSUE TITLE
Where the email is checked

### ISSUE THREAD

**Issue by PierBJX** [NukaPunk/API-Node-Mongo-Passport#1]
Hi,
I have changed the code in order to remove the API and the script password to make a very basic identification. If the password is not good it works.
However, if the mail address does not exist the application crashes.
I think I know where the problem is. 
In ../models/User.js : 
```
UserSchema.statics.getAuthenticated = function (email, password, cb) {

    this.findOne({email: email}, function (err, user) {
        if (err)
            return cb(err);
```
It's because the err is null but if the email is not found it should return an error ?

Thanks

**Comment by JosephScript** [comment]
You should check if the email is a valid email address on the server side. I'll add an example!

**Comment by JosephScript** [comment]
https://github.com/NukaPunk/API-Node-Mongo-Passport/blob/1a9490126d8373da006786ef1aba445d99e10733/config/passport.js#L105-L108
